### ISSUE TITLE
谱面转换问题

### ISSUE THREAD

**Issue by xMarioHux** [clansty/MaiChartManager#2]
我在转换谱面的时候发现我所有的tap绝赞都变成了普通tap，touch烟花特效被吃，以及部分星星错位（有1q4变成1qq4）的情况
以及，感谢作者大大，工具非常好用 \ ( ^ o ^) /

**Comment by clansty** [comment]
谱面文件发我看看？
我转换谱面用的是第三方的库，我已经给库修了很多问题了（（

**Comment by xMarioHux** [comment]
[普通disco.zip](https://github.com/user-attachments/files/16870760/disco.zip)
这个，红谱，紫的还没写完）
星星错位在2:07左右的位置

**Comment by clansty** [comment]
好的

**Comment by clansty** [comment]
> 以及PV是不是还不能导入呀

还没做，以后会有
现在 mod 可以把封面作为背景

**Comment by xMarioHux** [comment]
> > 以及PV是不是还不能导入呀
> 
> 还没做，以后会有 现在 mod 可以把封面作为背景

期待佬的后续更新！

**Comment by clansty** [comment]
诶，好了？

**Comment by xMarioHux** [comment]
> 诶，好了？

1.0.3应该是没有这个问题了，至少我转的时候没看到了
