### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by ck2739046** [clansty/MaiChartManager#6]
0. 我在使用tg群组ci build中的最新aquamai和zh.toml，以及最新版MaiChartManager

1. MaiChartManager管理mod意外造成toml变更
复现步骤：
将aquamai.zh.toml改名为aquamai.toml放入游戏文件夹，点击MaiChartManager的Mod管理
不进行任何设置，直接退出，然后发现toml原来的175-203行被删除

2. MaiChartManager音频转码音量问题
如果原始mp3音量过小，MaiChartManager转出来的谱面音量维持不变，也是很小，能否考虑增加自动调整音量的功能(

**Comment by clansty** [comment]
CI 版本的 AquaMai 是预览测试版，并没有设计上和非匹配版本的 MCM 一起使用。如果要用 CI 版本 AquaMai 就不应该用 MCM 编辑配置了，目前 MCM 只能编辑它绑定的那版本 AquaMai 的配置。但是下个版本的 MCM 将优化这个情况并且最大限度支持编辑较旧版本的 AquaMai 配置并迁移

音量过小那是你的 mp3 本来就音量过小，就算是主流的音频播放器都没有音量均衡功能
